version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.Frontend
    ports:
      - "3000:80"
    networks:
      - app-network

  backend:
    build:
      context: .
      dockerfile: Dockerfile.Backend
    ports:
      - "5107:80" 
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
